### ISSUE TITLE
Executable path in systemd service file

### ISSUE THREAD

**Issue by h3ndrik** [ericgaspar/libretranslate_ynh#1]
Hey, thank you for starting work on this app!

I found a problem though:

The /etc/systemd/system/libretranslate.service file tries to execute:
`/var/www/libretranslate/.venv/libretranslate`

However, on my system the binary has been installed to
`/var/www/libretranslate/.venv/bin/libretranslate`

Seems to work with this change.

**Comment by ericgaspar** [comment]
Thanks for pointing this out!
I will transfer the package to YunoHost repo so that more users can debug

**Comment by h3ndrik** [comment]
great. thanks
